deployment:
  svc: true
  bff: true
  api: true
  ui: true
  legacy: true

product:
  info:
    data:
      description: "OneCX Workspace"
      imageUrl: ""
      iconName: desktop
      displayName: "OneCX Workspace"
      basePath: /workspace
      provider: "OneCX Team"
      classifications: [ "Administration" ]
