deployment:
  svc: true
  bff: true
  
product:
  info:
    data:
      description: "OneCX Workspace"
      imageUrl: ""
      iconName: "gear"
      displayName: "OneCX Workspace"
      basePath: "/workspace"
