name: Update user documentation
on:
  push:
    branches: [ main ]
    paths:
      - 'userdocs/**'
jobs:
  release:
    uses: onecx/ci-common/.github/workflows/documentation.yml@v1
    secrets: inherit
    with:
      docs: userdocs
